---
# Source: default-ingress/templates/gateway.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-dotnet-works-com-ingress
  namespace: 'istio-system'
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  # https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/
  # ingressClassName: 'istio-gateway'
  tls:
  - hosts:
    - '*.dotnet-works.com'
    - 'dotnet-works.com'
    # For the istio gateway to use this the secret
    # it must be in the same namespace as the istio-ingress-gateway (normally istio-system)
    # Cert-manager can still be used to get and renew certificates 
    # But note that the certificates themselves need to be created in the namespace of the 
    # istio-ingress-gateway as well. See: https://istio.io/latest/docs/ops/integrations/certmanager/ 
    secretName: dotnet-works-com-wildcard-tls
---
# Source: default-ingress/templates/gateway.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-freelancedirekt-nl-ingress
  namespace: 'istio-system'
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  # https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/
  # ingressClassName: 'istio-gateway'
  tls:
  - hosts:
    - '*.freelancedirekt.nl'
    - 'freelancedirekt.nl'
    # For the istio gateway to use this the secret
    # it must be in the same namespace as the istio-ingress-gateway (normally istio-system)
    # Cert-manager can still be used to get and renew certificates 
    # But note that the certificates themselves need to be created in the namespace of the 
    # istio-ingress-gateway as well. See: https://istio.io/latest/docs/ops/integrations/certmanager/ 
    secretName: freelancedirekt-nl-wildcard-tls
---
# Source: default-ingress/templates/gateway.yml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-dotnet-works-com-istio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: dotnet-works-com-wildcard-tls # must be the same as secret
    hosts:
    - '*.dotnet-works.com'
---
# Source: default-ingress/templates/gateway.yml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-freelancedirekt-nl-istio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: freelancedirekt-nl-wildcard-tls # must be the same as secret
    hosts:
    - '*.freelancedirekt.nl'
---
# Source: default-ingress/templates/gateway.yml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dotnet-works-com-virtualservice
spec:
  hosts:
  - '*.dotnet-works.com'
  gateways:
  - default-dotnet-works-com-istio-gateway
  http:
  - match:
    - uri:
        regex: /?(.*)
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 5000
        host: default-backend-service
---
# Source: default-ingress/templates/gateway.yml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: freelancedirekt-nl-virtualservice
spec:
  hosts:
  - '*.freelancedirekt.nl'
  gateways:
  - default-freelancedirekt-nl-istio-gateway
  http:
  - match:
    - uri:
        regex: /?(.*)
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 5000
        host: default-backend-service
