apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: freelancedirekt-nl-wildcard-cert
  namespace: default
spec:
  secretName: freelancedirekt-nl-wildcard-tls
  issuerRef:
    # this references the issuer name in the issuer-letsencrypt-staging.yml file
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.freelancedirekt.nl"
  dnsNames:
    - "*.freelancedirekt.nl"