apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Since the tls section has been commented out and we rely on the wildcard certificate this is not needed anymore
    # cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  # Leaving this here in combination with the cert-manager.io/cluster-issuer annotation will issue a new tls certificate for example.dotnet-works.com
  # By leaving is out we can use the generic Ingress configuration and default TLS certificate for *.dotnet-works.com
#  tls:
#    - hosts:
#        - example.dotnet-works.com
#      secretName: example-dotnet-works-com-tls
  rules:
    - host: example.dotnet-works.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: default-backend-service
                port:
                  number: 5000