{{- if .Values.IstioGatewayEnabled -}}
{{- range $domainName := $.Values.Domains }}
{{- $domainNameWithoutDots := regexReplaceAll "\\." $domainName "-" -}}
{{- $testDomainName := print "test." $domainName -}}
{{- $testDomainNameWithoutDots := print "test-" $domainName -}}
{{- $gatewayName := print "default-" $domainNameWithoutDots "-istio-gateway" -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $gatewayName }}
  annotations:
    # https://cert-manager.io/docs/usage/gateway/
    # not working at the moment because istio does not support setting tls.mode to TERMINATE at the moment
    cert-manager.io/cluster-issuer: '{{ $.Values.CertIssuer }}'
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ $domainNameWithoutDots }}-wildcard-tls # must be the same as secret
    hosts:
    - '*.{{ $domainName }}'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $domainNameWithoutDots }}-virtualservice
spec:
  hosts:
  - '*.{{ $domainName }}'
  gateways:
  - {{ $gatewayName }}
  http:
  - match:
    - uri:
        regex: /?(.*)
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: {{ $.Values.BackendPort }}
        host: {{ $.Values.BackendService }}
---
{{- end }}
{{- end }}