{{- range $domainName := $.Values.Domains }}
{{- $domainNameWithoutDots := regexReplaceAll "\\." $domainName "-" -}}
{{- $testDomainName := print "test." $domainName -}}
{{- $testDomainNameWithoutDots := print "test-" $domainName -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-{{ $domainNameWithoutDots }}-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # Rewrite url to always go to /
    # This metadata will only apply to the rules mentioned in this file
    # Othe Ingress services can have their own annotations
    nginx.ingress.kubernetes.io/rewrite-target: /
    # By setting the cluster-issuer the shim will not automatically create certs
    # When adding other ingress services you will usually not specify this annotation
    # That means that the default wildcard certificate will be used
    cert-manager.io/cluster-issuer: '{{ $.Values.CertIssuer }}'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - '*.{{ $domainName }}'
    - '{{ $domainName }}'
    secretName: {{ $domainNameWithoutDots }}-wildcard-tls
  rules:
    - host: '*.{{ $domainName }}'
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.BackendService }}
                port:
                  number: {{ $.Values.BackendPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $testDomainNameWithoutDots }}-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Since the tls section has been commented out and we rely on the wildcard certificate this is not needed anymore
    # cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  # Leaving this here in combination with the cert-manager.io/cluster-issuer annotation will issue a new tls certificate for {{$testDomainName}}
  # By leaving is out we can use the generic Ingress configuration and default TLS certificate for *.{{ $domainName }}
#  tls:
#    - hosts:
#        - {{ $testDomainName }}
#      secretName: {{ $testDomainNameWithoutDots }}-tls
  rules:
    - host: {{ $testDomainName }}
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.BackendService }}
                port:
                  number: {{ $.Values.BackendPort }}
---
{{- end }}