version: '3'
services:
  gksdk:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # using this image takes longer to download
    # but once downloaded no need to install kubectl anymore afterwards
    # so overall a better choice I think
    # image: google/cloud-sdk:latest
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      # better if this is different from the WORKDIR in the docker file
      # if not, files added when running commands in the container end up on the host and in the git repo
      - .:/src