version: '3.7'
services:
  eksctl:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: doctl
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      # better if this is different from the WORKDIR in the docker file
      # if not, files added when running commands in the container end up on the host and in the git repo
      - .:/src