name: Deploy to Azure Kubernetes Engine (AKS)

on:
  push:
    branches:
      - master

env:
  DOCKER_ID: dnw2022
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
  # AKS_SERVICE_PRINCIPAL_NAME: sp-dnw
  AKS_APP_ID: ${{ secrets.AKS_APP_ID }}
  AKS_PASSWORD: ${{ secrets.AKS_PASSWORD }}
  AKS_TENANT_ID: ${{ secrets.AKS_TENANT_ID }}
  AKS_CLUSTER_NAME: 'cluster-dnw-aks'
  AKS_RESOURCE_GROUP: 'rg-dnw'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See: https://github.com/Azure/login#configure-deployment-credentials
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # https://github.com/Azure/setup-kubectl
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v2.0
        with:
          version: 'v1.21.7'

      # https://github.com/Azure/aks-set-context
      # This is a pre-release and it will not show up in the marketplace directly
      # If you go to the marketplace with the link in the repo you will see it
      - name: Set Context for Azure Kubernetes Cluster using azure/aks-set-context@v1 action
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}

      - name: Install and configure GK sdk
        run: |-
          kubectl version

      # - name: Deploy to AKS
      #   run: ./setup-certs.sh