name: Deploy to Digital Ocean (DO) Kubernetes

on:
  push:
    branches:
      - master

env:
  DOCKER_ID: dnw2022
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
  DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
  DO_CLUSTER_NAME: cluster-dnw

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DO_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.DO_CLUSTER_NAME }}

      - name: Give execute permissions for shell script
        run: chmod +x ./setup-certs.sh

      # Manually doing all this causes issues
      # In the next step the shell script cannot find doctl
      # I am not sure where to install things so they can be found in next steps
      # Something to find out later
      # See: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
      # - name: Install & configure tools
      #   run: |-
      #     # Install kubectl
      #     # curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      #     curl -LO "https://dl.k8s.io/release/v1.23.3/bin/linux/amd64/kubectl"
      #     chmod +x kubectl

      #     # Install doctl
      #     curl -LO "https://github.com/digitalocean/doctl/releases/download/v1.70.0/doctl-1.70.0-linux-amd64.tar.gz"
      #     tar -xf doctl-1.70.0-linux-amd64.tar.gz
      #     chmod +x doctl
      #     export PATH=$PATH:$(pwd)

      #     # Configure doctl
      #     doctl auth init -t "${{ env.DO_ACCESS_TOKEN }}"
      #     doctl kubernetes cluster kubeconfig save ${{ env.DO_CLUSTER_NAME }}
          
      #     # Give execute permissions for shell script
      #     chmod +x ./setup-certs.sh

      - name: Deploy to Digital Ocean
        run: ./setup-certs.sh