name: Deploy to Digital Ocean Kubernetes Service (DOKS)

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOCKER_ID: dnw2022
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
  DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
  DO_CLUSTER_NAME: cluster-dnw

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push images to Docker Hub
        run: |-
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
          TAG=dnw2022/default-backend:latest
          docker build -t $TAG -f ./default-backend/Dockerfile  ./default-backend
          docker push $TAG

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DO_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.DO_CLUSTER_NAME }}

      - name: Store secrets with certificates in cluster
        run: |-
          # apply yml with the secret containing the dotnet-works.com wildcard cert 
          echo "${{ secrets.DNW_CERT_SECRET }}" | base64 --decode > ./dnw-cert-secret.yml
          kubectl apply -f ./dnw-cert-secret.yml

          # apply yml with the secret containing the freelancedirekt.nl wildcard cert 
          echo "${{ secrets.FLD_CERT_SECRET }}" | base64 --decode > ./fld-cert-secret.yml
          kubectl apply -f ./fld-cert-secret.yml

      # https://github.com/marketplace/actions/helm-tool-installer
      - name: Helm tool installer
        uses: Azure/setup-helm@v2.0

      - name: Deploy to AKS
        run: |-
          helm upgrade default-backend ./k8s/helm/default-backend --install
          helm upgrade cert-issuers ./k8s/helm/cert-issuers --install
          helm upgrade default-ingress ./k8s/helm/default-ingress --install

          kubectl rollout restart deployment default-backend-deployment